compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

packageExtensions:
  "@octokit/plugin-retry@5.0.1":
    dependencies:
      "@octokit/request-error": 3.0.3

yarnPath: .yarn/releases/yarn-4.0.2.cjs
